config/routes.rb
Rails.application.routes.draw do
  resources :devices

  devise_for :users
  root 'pages#home'

  get "welcome" => "pages#welcome"
  
  post "test" => "pages#test"
  get "test" => "pages#test"
  
  post "testsend" => "pages#testsend"
  post "registermobile" => "pages#registermobile"

  devise_scope :user do
    post "mobilelogin" => "mobilecontroller#create"
    delete "mobilelogout" => "mobilecontroller#destroy"
  end

end

app/models/device.rb
class Device < ActiveRecord::Base
	validates :name, presence: true
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  has_many :devices
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
 	before_filter :configure_permitted_parameters, if: :devise_controller?
 	
 	def after_sign_in_path_for(user)
  	devices_path
	end


	protected

	 def configure_permitted_parameters
	   devise_parameter_sanitizer.for(:sign_up) << :name
	   devise_parameter_sanitizer.for(:account_update) << :name
	 end
  
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user,only: [:edit, :update, :destroy, :show]

  respond_to :html

  def index
    @devices = Device.all
    respond_with(@devices)
  end

  def show
    respond_with(@device)
  end

  def new
    @device = current_user.devices.build
    respond_with(@device)
  end

  def edit
  end

  def create
    @device = current_user.devices.build(device_params)
    @device.save
    respond_with(@device)
  end

  def update
    @device.update(device_params)
    respond_with(@device)
  end

  def destroy
    @device.destroy
    respond_with(@device)
  end

  private
    def set_device
      @device = Device.find(params[:id])
    end

    def correct_user
      if current_user.name != "admin"
        @device = current_user.devices.find_by(id: params[:id])
        redirect_to devices_path, notice: "Not authorized" if @device.nil?        
      end
    end

    def device_params
      params.require(:device).permit(:name, :owner)
    end
end

app/controllers/mobilecontroller_controller.rb
class MobilecontrollerController < Devise::SessionsController
  skip_before_filter :verify_authenticity_token , :only => [:create]

  respond_to :json

  def create
    warden.authenticate!(:scope => resource_name, :recall => "#{controller_path}#failure")
    render :status => 200,
           :json => { :success => true,
                      :info => "Logged in",
                      :data => { :userID => User.where(email: params[:user][:email]).take.id } }
  end

  def destroy
    warden.authenticate!(:scope => resource_name, :recall => "#{controller_path}#failure")
    current_user.update_column(:authentication_token, nil)
    render :status => 200,
           :json => { :success => true,
                      :info => "Logged out",
                      :data => {} }
  end

  def failure
    render :status => 401,
           :json => { :success => false,
                      :info => "Login Failed",
                      :data => {} }
  end

  def generate_authentication_token
    loop do
      token = Devise.friendly_token
      break token unless User.where(authentication_token: token).first
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	protect_from_forgery with: :null_session
	skip_before_filter :verify_authenticity_token, :only => [:test,:registermobile]
	respond_to :html
  
  def welcome
  end
  
  def home  	
  end
  
  def test
  	
  	@string = "not set"
  	if params != nil

        @device = Device.new

  			@device.name = params[:deviceName]
  			@device.regID = params[:deviceID]

  			if @device.save
          @string = "device saved"
    				# do something when save is successful
  			else
          @string= "error"
    				# handle the case when it doesn't save properly
  			end


	      @string = params[:deviceID] 
        #provare a commentare la linea sotto
	      render :json =>{:data => @string, :data2 => params[:deviceID]}
	      #puts response {render :layout => false}
    end
   end

   def testsend
    @deviceID = 0
    @message = "my message"
    if params != nil
        @deviceID = params[:deviceID]
        @message = params[:urlImage]

        require 'gcm'

        gcm = GCM.new("AIzaSyD2DDS4y3TVNGHIvUwNDf65BpW5lEXFjpg")
        # you can set option parameters in here
        #  - all options are pass to HTTParty method arguments
        #  - ref: https://github.com/jnunemaker/httparty/blob/master/lib/httparty.rb#L40-L68
        #  gcm = GCM.new("my_api_key", timeout: 3)
        puts "TRYING TO RESPOND to #{@deviceID}, logs!"
        registration_ids= ["#{@deviceID}"] # an array of one or more client registration IDs
        #options = {data: @message}
        options = {
          'data' => {
            'message' => @message
          }
        }
        response = gcm.send(registration_ids, options)
        puts "GCM SEND RESPONSE, logs!"

        #provare a commentare la linea sotto
        #render :json =>{:data => @string}
        #puts response {render :layout => false}
    end
   end

  def registermobile
    @message = "my message"
    if params != nil

        @device = Device.new
        @device.name = params[:device][:deviceName]
        @device.regID = params[:device][:deviceID]
        @device.user_id = params[:device][:deviceOwner]

        if @device.save!
          @string = "device saved"
            # do something when save is successful
            render :status => 200,
            :json => { :success => true,
                      :info => "Device registration compleated",
                      :data => {:data => @string} }
        else
          @string= "error"
          render :status => 401,
          :json => { :success => false,
                      :info => "Device registration failed",
                      :data => {:data => @string} }
        end
        
        
    end
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/mobilecontroller_helper.rb
module MobilecontrollerHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<h1>Listing devices</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <%# TODO:fix name admin -> make it user attribute %>
      <% if (current_user.name == "admin") %>
      <tr>
        <td>
          <% if device.user_id != nil %>
            <%= User.find(device.user_id).name %>  
          <% end %>
          </td>        
        <td><%= device.name %></td>
        <td>       
          <%= form_tag(testsend_path, class:'form-inline') do %>
            <%= text_field_tag(:urlImage, "Url image", class:'form-control', onclick:"$(this).removeAttr('value')") %>
            <%# TODO:fix this "hidden" %>
            <%= hidden_field_tag :deviceID, device.regID %>
            <%= submit_tag("Nig it!",class:'btn btn-default') %>
          <% end %>
        </td>
        <td>
          <%= link_to edit_device_path(device) do %>
            Edit <span class="glyphicon glyphicon-edit"></span>  
          <% end %>
        </td>
        <td>  
          <%= link_to device, method: :delete, data: { confirm: 'Are you sure?' } do %>
            Delete <span class="glyphicon glyphicon-trash"></span>
          <% end %>
        </td>
      </tr>
      <% end %>
      <% if (current_user.name != "admin" && device.user == current_user) %>
      <tr>        
        <td><%= device.name %></td>
        <td>       
          <%= form_tag(testsend_path, class:'form-inline') do %>
            <%= text_field_tag(:urlImage, "Url image", class:'form-control', onclick:"$(this).removeAttr('value')") %>
            <%# TODO:fix this "hidden" %>
            <%= hidden_field_tag(:deviceID, device.regID) %>
            <%= submit_tag("Nig it!",class:'btn btn-default') %>
          <% end %>
        </td>
        <td>
          <%= link_to edit_device_path(device) do %>
            Edit <span class="glyphicon glyphicon-edit"></span>  
          <% end %>
        </td>
        <td>  
          <%= link_to device, method: :delete, data: { confirm: 'Are you sure?' } do %>
            Delete <span class="glyphicon glyphicon-trash"></span>
          <% end %>
        </td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
<%= link_to 'New Device', new_device_path %>
<% end %>

app/views/devices/new.html.erb
<h1>New device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @device.name %>
</p>


<% if @device.user == current_user %>
<%= link_to 'Edit', edit_device_path(@device) %> |
<% end %>
<%= link_to 'Back', devices_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if user_signed_in? %>
        <%= link_to "NigMeApp", devices_path, class: "navbar-brand" %>
      <% else %>
        <%= link_to "NigMeApp", root_path, class: "navbar-brand" %>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About", "#" %></li>
        <% if user_signed_in? %>
          <li><%= link_to current_user.name, edit_user_registration_path, {:style => 'padding-right: 0px;'} %></li>
          <li><%= link_to raw('<span class="glyphicon glyphicon-cog"></span>'), edit_user_registration_path, {:style => 'padding-left: 0px;'} %></li>
          <li><%= link_to raw('Log out <span class="glyphicon glyphicon-log-out"></span>'), destroy_user_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nigmeappweb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<%= render 'layouts/header' %>
	<% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-info") %>
	<% end %>
	<div class="container">
		<%= yield %>
	</div>

</body>
</html>

app/views/mobilecontroller/login.html.erb
hi

app/views/pages/Stest.html.erb
<%= @string %>
<%= @values %>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<% if user_signed_in? %>
    <%= link_to "my devices", devices_path %>
  <% else %>
		<h1>Welcome folks</h1>
		<h4>(still an alpha version, <%= link_to "download", "https://www.dropbox.com/s/8c0l4ntj7neowtv/Nigmeapp.apk?dl=1" %> the .apk)</h4>
		<p> <%= link_to "login", new_user_session_path, class: "btn btn-primary" %> or <%= link_to "sign up", new_user_registration_path, class: "btn btn-primary" %> </p>
	<% end %> 
</div>

app/views/pages/test.html.erb
<%= @string %>
<%= @values %>

app/views/pages/testsend.html.erb
hello!
<br>
device id = <%= @deviceID %>
<br>
url = <%= @message %>

app/views/pages/welcome.html.erb
<h1>Beautiful welcome page</h1>